# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_featurecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
        ),
    ]
