# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_feature_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='completed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='in_progress_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='incomplete_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
