# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bugcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='fixed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='in_progress_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='open_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
